// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA48r7uQWZLwAzm3hSceRegEJMM5PdvHVE',
    appId: '1:144961365920:web:e841eed3fbc2ae643f26c5',
    messagingSenderId: '144961365920',
    projectId: 'dfbus-458903',
    authDomain: 'dfbus-458903.firebaseapp.com',
    storageBucket: 'dfbus-458903.firebasestorage.app',
    measurementId: 'G-17L39NYHTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipSFtoErQ1bTY2YxzbxdzknFZuEk4Kxc',
    appId: '1:144961365920:android:48c49062045f16863f26c5',
    messagingSenderId: '144961365920',
    projectId: 'dfbus-458903',
    storageBucket: 'dfbus-458903.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA48r7uQWZLwAzm3hSceRegEJMM5PdvHVE',
    appId: '1:144961365920:web:c608ec16786a551d3f26c5',
    messagingSenderId: '144961365920',
    projectId: 'dfbus-458903',
    authDomain: 'dfbus-458903.firebaseapp.com',
    storageBucket: 'dfbus-458903.firebasestorage.app',
    measurementId: 'G-0QQFWM11CL',
  );

}